version: '3.8'

services:
  celery_worker:
    environment:
      # 연장장 허용은 유지하되, 필터를 더 보수적으로
      RTH_ONLY: "false"
      EXTENDED_PRICE_SIGNALS: "true"
      
      # 연장장 필터를 더 까다롭게
      EXT_MIN_DOLLAR_VOL_5M: "500000"    # 100000 → 500000 (더 큰 유동성 필요)
      EXT_MAX_SPREAD_BP: "100"           # 200 → 100bp (1% 스프레드로 제한)
      EXT_COOLDOWN_MIN: "15"             # 2 → 15분 (충분한 쿨다운)
      
      # 정규장도 조금 더 보수적으로
      SIGNAL_CUTOFF: "0.6"               # 기본보다 높은 품질
      COOLDOWN_MIN: "10"                 # 10분 쿨다운

  celery_beat:
    environment:
      RTH_ONLY: "false"
      EXTENDED_PRICE_SIGNALS: "true"
      SIGNAL_CUTOFF: "0.6"
