version: '3.8'
services:
  celery_worker:
    command: >
      sh -lc 'exec celery -A app.jobs.scheduler worker --loglevel=${LOG_LEVEL:-DEBUG} -P solo -c 1 -I app.hooks.autoinit'
    environment:
      LOG_LEVEL: DEBUG
      CELERY_IMPORTS: app.hooks.autoinit
      CELERY_ACKS_LATE: "false"
      CELERYD_PREFETCH_MULTIPLIER: "1"
  celery_beat:
    environment:
      LOG_LEVEL: DEBUG
